### ISSUE TITLE
track number of times used

### ISSUE THREAD

**Issue by clararaubertas** [Parallactic/calling-congress#8]
scripts should track how often someone has used them -- then maybe we put the most-used at the top on the front page

**Comment by faraocious** [comment]
Do we have any way to know that a call is actually happening? or is the idea here to increment every time a script is rendered?

**Comment by clararaubertas** [comment]
Yeah, I'm thinking maybe an "I did it!" button? we don't have a way to literally verify that there was an actual call, but I think that self-reporting is adequate here.

**Comment by faraocious** [comment]
I like that idea.

On Fri, Nov 18, 2016 at 10:02 AM Clara Raubertas <notifications@github.com>
wrote:

Yeah, I'm thinking maybe an "I did it!" button? we don't have a way to
literally verify that there was an actual call, but I think that
self-reporting is adequate here.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Parallactic/calling-congress/issues/8#issuecomment-261568217>,
or mute the thread
